FROM python:3.11-slim

# Prevents Python from buffering stdout/stderr
ENV PYTHONUNBUFFERED=1
ENV PYTHONUSERBASE=/home/sandbox/.local
ENV PATH=$PATH:/home/sandbox/.local/bin
ENV PIP_ONLY_BINARY=:all:
ENV PIP_PREFER_BINARY=1

# Create non-root user for safety
RUN useradd -m sandbox
USER sandbox
WORKDIR /home/sandbox

# Install dependencies
RUN pip install --user --no-cache-dir --pre \
    numpy \
    pandas \
    matplotlib \
    aiocache>=0.12.3 \
    aiomysql>=0.2.0 \
    Jinja2>=3.1.6 \
    mysql-connector-python>=9.1.0 \
    pandas>=2.2.2 \
    psycopg2-binary>=2.9.10 \
    suql>=1.1.9b1 \
    tabulate>=0.9.0 \
    scikit-learn

# Optional: disable access to network for safety when running untrusted code
# ENV PYTHONSAFETY=1

# Keeps the container alive between executions
CMD ["tail", "-f", "/dev/null"]
